# Product Definitions
  Product:
    type: object
    properties:
      packageName:
        type: string
        description: package name
      products:
        type: array
        items:
          type: object
          properties:
              productCategory:
                type: string
                description: product Category id description
              isMainProduct:
                type: boolean
                description: check if its Main product
              name:
                type: string
                description: product name
              imageUrl:
                type: string
                description: imageUrl
              packageID:
                type: string
                description: id of the package
              description:
                type: string
                description: product description
