# Product Definitions
  Product:
    type: object
    properties:
      length:
        type: number
        require: true
        description: package durations
      packageName:
        type: string
        description: package name
      sellingCycle:
        type: number
        description: number of days that the product will sell
        required: true
      watingCycle:
        type: number
        description: number of day the produce have to wait before going back to the selling cycle
        required: true
      products:
        type: array
        items:
          type: object
          properties:
            type:
              type: string
              enum: [main, upsell, downsell, order-bump, cross-sell]
              description: selected product type
            isMainProduct:
              type: boolean
              description: check if its Main product
            hasAirportTransfer:
              type: boolean
              description: Whether product has airtport transfer feature
            cancellationDaysLimit:
              type: number
              description: Number of days at which no refund can be processed for product
            name:
              type: string
              description: product name
            imageUrl:
              type: string
              description: imageUrl
            packageID:
              type: string
              description: id of the package
            description:
              type: string
              description: product description

  Products:
    type: array
    items:
      type: object
      properties:
        type:
          type: string
          description: product type
          enum: [main, upsell, downsell, order-bump, cross-sell]
        sellingCycle:
          type: number
          description: number of days that the product will sell
          required: true
        watingCycle:
          type: number
          description: number of day the produce have to wait before going back to the selling cycle
          required: true
        endDate:
          type: string
          description: End date for product life cycle
        startDate:
          type: string
          description: start date for the products life cycle for the first or current cycle
        statues:
          type: string
          enum: [active, wating, expired]
          description: current status of life cycle
        isMainProduct:
          type: boolean
          description: check if its Main product
        hasAirportTransfer:
          type: boolean
          description: Whether product has airtport transfer feature
        name:
          type: string
          description: product name
        imageUrl:
          type: string
          description: imageUrl
        packageID:
          type: string
          description: id of the package
        description:
          type: string
          description: product description

  singleProducts:
    type: object
    properties:
      type:
        type: string
        description: product type
        enum: [main, upsell, downsell, order-bump, cross-sell]
      sellingCycle:
        type: number
        description: number of days that the product will sell
        required: true
      watingCycle:
        type: number
        description: number of day the produce have to wait before going back to the selling cycle
        required: true
      endDate:
        type: string
        description: End date for product life cycle
      startDate:
        type: string
        description: start date for the products life cycle for the first or current cycle
      statues:
        type: string
        enum: [active, wating, expired]
        description: current status of life cycle
      isMainProduct:
        type: boolean
        description: check if its Main product
      hasAirportTransfer:
        type: boolean
        description: Whether product has airtport transfer feature
      name:
        type: string
        description: product name
      imageUrl:
        type: string
        description: imageUrl
      packageID:
        type: string
        description: id of the package
      description:
        type: string
        description: product description