  # Product Definitions
  Product:
    type: object
    properties:
      packageName:
        type: string
        description: package name
      products:
        type: array
        items:
          type: object
          properties:
            type:
              type: string
              enum: [main, upsell, downsell, order-bump, cross-sell]
              description: selected product type
            isMainProduct:
              type: boolean
              description: check if its Main product
            hasAirportTransfer:
              type: boolean
              description: Whether product has airtport transfer feature
            cancellationDaysLimit:
              type: mumber
              description: Number of days at which no refund can be processed for product
            name:
              type: string
              description: product name
            imageUrl:
              type: string
              description: imageUrl
            packageID:
              type: string
              description: id of the package
            description:
              type: string
              description: product description
            marketingExpiryDate:
              description: marketing expiry date set by vendor 
              type: date
            marketingPriority:
              description: marketing priority set by admin

  Products:
    type: array
    items:
      type: object
      properties:
        type:
          type: string
          description: product type
          enum: [main, upsell, downsell, order-bump, cross-sell]
        isMainProduct:
          type: boolean
          description: check if its Main product
        hasAirportTransfer:
          type: boolean
          description: Whether product has airtport transfer feature
        name:
          type: string
          description: product name
        imageUrl:
          type: string
          description: imageUrl
        packageID:
          type: string
          description: id of the package
        description:
          type: string
          description: product description
