  # Product Definitions
  Product:
    type: object
    properties:
      packageName:
        type: string
        description: package name
      sellingCycle:
        type: number
        description: number of day the product will sell
      waitingCycle:
        type: number
        description: number of day the product will wait before it gose back into the selling cycle
      products:
        type: array
        items:
          type: object
          properties:
            type:
              type: string
              enum: [main, upsell, downsell, order-bump, cross-sell]
              description: selected product type
            isMainProduct:
              type: boolean
              description: check if its Main product
            hasAirportTransfer:
              type: boolean
              description: Whether product has airtport transfer feature
            cancellationDaysLimit:
              type: integer
              description: Number of days at which no refund can be processed for product
            name:
              type: string
              description: product name
            imageUrl:
              type: string
              description: imageUrl
            packageID:
              type: string
              description: id of the package
            description:
              type: string
              description: product description
            marketingExpiryDate:
              description: marketing expiry date set by vendor 
              type: date
            marketingPriority:
              type: integer
              description: marketing priority set by admin
            adultPrice:
              type: integer
              description: adult price for product
            childrenPrice:
              type: integer
              description: children price for product
            customPrices:
              type: array
              items:
                type: object
                properties:
                  range:
                    type: array
                    items:
                      type: integer
                      description: quantity range
                  prices:
                    type: object
                    properties:
                      adult:
                        type: integer
                        description: Adult price for this range
                      children:
                        type: integer
                        description: Children price for this range
  Products:
    type: array
    items:
      type: object
      properties:
        sellingCycle:
          type: number
          description: number of day the product will sell
        waitingCycle:
          type: number
          description: number of day the product will wait before it gose back into the selling cycle
        type:
          type: string
          description: product type
          enum: [main, upsell, downsell, order-bump, cross-sell]
        isMainProduct:
          type: boolean
          description: check if its Main product
        hasAirportTransfer:
          type: boolean
          description: Whether product has airtport transfer feature
        name:
          type: string
          description: product name
        imageUrl:
          type: string
          description: imageUrl
        packageID:
          type: string
          description: id of the package
        description:
          type: string
          description: product description
