  # Product Definitions
  Product:
    type: object
    properties:
      totalSlots:
        type: number
        description: total avalable slots
      slotsUsed:
        type: number
        description: total number of slots used
      slotsLeft:
        type: number
        description: total number of slots left
      packageName:
        type: string
        description: package name
      sellingCycle:
        type: number
        description: number of day the product will sell
      waitingCycle:
        type: number
        description: number of day the product will wait before it gose back into the selling cycle
      products:
        type: array
        items:
          type: object
          properties:
            type:
              type: string
              enum: [main, upsell, downsell, order-bump, cross-sell]
              description: selected product type
            isMainProduct:
              type: boolean
              description: check if its Main product
            hasAirportTransfer:
              type: boolean
              description: Whether product has airtport transfer feature
            cancellationDaysLimit:
              type: integer
              description: Number of days at which no refund can be processed for product
            name:
              type: string
              description: product name
            imageUrl:
              type: string
              description: imageUrl
            packageID:
              type: string
              description: id of the package
            description:
              type: string
              description: product description
            marketingExpiryDate:
              description: marketing expiry date set by vendor 
              type: string
            marketingPriority:
              type: integer
              description: marketing priority set by admin
            price:
              type: object
              properties:
                adult:
                  type: integer
                  description: Vendor adult price
                children:
                  type: integer
                  description: Children price
            customPrices:
              type: array
              items:
                type: object
                properties:
                  range:
                    type: array
                    items:
                      type: integer
                      description: quantity range
                  prices:
                    type: object
                    properties:
                      adult:
                        type: integer
                        description: Vendor adult price for this range
                      children:
                        type: integer
                        description: Children price for this range

                                                                     
  Products:
    type: array
    items:
      type: object
      properties:
        totalSlots:
          type: number
          description: total avalable slots
        slotsUsed:
          type: number
          description: total number of slots used
        slotsLeft:
          type: number
          description: total number of slots left
        sellingCycle:
          type: number
          description: number of day the product will sell
        waitingCycle:
          type: number
          description: number of day the product will wait before it gose back into the selling cycle
        type:
          type: string
          description: product type
          enum: [main, upsell, downsell, order-bump, cross-sell]
        isMainProduct:
          type: boolean
          description: check if its Main product
        hasAirportTransfer:
          type: boolean
          description: Whether product has airtport transfer feature
        name:
          type: string
          description: product name
        imageUrl:
          type: string
          description: imageUrl
        packageID:
          type: string
          description: id of the package
        description:
          type: string
          description: product description

  ProductLifeCycle:
    type: object
    properties:
      totalSlots:
        type: number
        description: total avalable slots
      slotsUsed:
        type: number
        description: total number of slots used
      slotsLeft:
        type: number
        description: total number of slots left
      _id:
        type: string
        description: cycle id
      product:
        type: string
        description: id of the product that owns the cycle
      startDate:
        type: string
        description: cycle start page
      endDate:
        type: string
        description: cycle start page
      sellingCycle:
        type: number
        description: number of day the product will sell
      waitingCycle:
        type: number
        description: number of day the product will wait before it gose back into the selling cycle
      status:
        type: string
        description: current status of the cycle
        enum: [active, canceled, paused, waiting, expired]

  singleProducts:
    type: object
    properties:
      totalSlots:
        type: number
        description: total avalable slots
        required: true
      slotsUsed:
        type: number
        description: total number of slots used
        required: true
      slotsLeft:
        type: number
        description: total number of slots left
        required: true
      type:
        type: string
        description: product type
        enum: [main, upsell, downsell, order-bump, cross-sell]
      sellingCycle:
        type: number
        description: number of days that the product will sell
        required: true
      waitingCycle:
        type: number
        description: number of day the produce have to wait before going back to the selling cycle
        required: true
      endDate:
        type: string
        description: End date for product life cycle
      startDate:
        type: string
        description: start date for the products life cycle for the first or current cycle
      status:
        type: string
        enum: [active, waiting, expired]
        description: current status of life cycle
      isMainProduct:
        type: boolean
        description: check if its Main product
      hasAirportTransfer:
        type: boolean
        description: Whether product has airtport transfer feature
      name:
        type: string
        description: product name
      imageUrl:
        type: string
        description: imageUrl
      packageID:
        type: string
        description: id of the package
      description:
        type: string
        description: product description

  slot:
    type: object
    properties:
      totalSlots:
        type: number
        description: total avalable slots